#ifndef __H_KEYBOARD__
#define __H_KEYBOARD__

#define KEY_GRP_ESC        (0)
#define KEY_GRP_1          (0)
#define KEY_GRP_2          (0)
#define KEY_GRP_3          (0)
#define KEY_GRP_4          (0)
#define KEY_GRP_5          (0)
#define KEY_GRP_6          (0)

#define KEY_GRP_7          (1)
#define KEY_GRP_8          (1)
#define KEY_GRP_9          (1)
#define KEY_GRP_0          (1)
#define KEY_GRP_MINUS      (1)
#define KEY_GRP_HAT        (1)
#define KEY_GRP_YEN        (1)
#define KEY_GRP_BS         (1)

#define KEY_GRP_TAB        (2)
#define KEY_GRP_Q          (2)
#define KEY_GRP_W          (2)
#define KEY_GRP_E          (2)
#define KEY_GRP_R          (2)
#define KEY_GRP_T          (2)
#define KEY_GRP_Y          (2)
#define KEY_GRP_U          (2)

#define KEY_GRP_I          (3)
#define KEY_GRP_O          (3)
#define KEY_GRP_P          (3)
#define KEY_GRP_ATMARK     (3)
#define KEY_GRP_SQBR_LEFT  (3)
#define KEY_GRP_CR         (3)
#define KEY_GRP_A          (3)
#define KEY_GRP_S          (3)

#define KEY_GRP_D          (4)
#define KEY_GRP_F          (4)
#define KEY_GRP_G          (4)
#define KEY_GRP_H          (4)
#define KEY_GRP_J          (4)
#define KEY_GRP_K          (4)
#define KEY_GRP_L          (4)
#define KEY_GRP_SEMICOLON  (4)

#define KEY_GRP_COLON      (5)
#define KEY_GRP_SQBR_RIGHT (5)
#define KEY_GRP_Z          (5)
#define KEY_GRP_X          (5)
#define KEY_GRP_C          (5)
#define KEY_GRP_V          (5)
#define KEY_GRP_B          (5)
#define KEY_GRP_N          (5)

#define KEY_GRP_M          (6)
#define KEY_GRP_COMMA      (6)
#define KEY_GRP_PERIOD     (6)
#define KEY_GRP_SLASH      (6)
#define KEY_GRP_UNDERSCORE (6)
#define KEY_GRP_SPACE      (6)
#define KEY_GRP_HOME       (6)
#define KEY_GRP_DEL        (6)

#define KEY_GRP_ROLLUP     (7)
#define KEY_GRP_ROLLDOWN   (7)
#define KEY_GRP_UNDO       (7)
#define KEY_GRP_LEFT       (7)
#define KEY_GRP_UP         (7)
#define KEY_GRP_RIGHT      (7)
#define KEY_GRP_DOWN       (7)
#define KEY_GRP_CLR        (7)

#define KEY_GRP_TEN7       (8)
#define KEY_GRP_TEN8       (8)
#define KEY_GRP_TEN9       (8)
#define KEY_GRP_TEN4       (8)

#define KEY_GRP_TEN5       (9)
#define KEY_GRP_TEN6       (9)
#define KEY_GRP_TEN1       (9)
#define KEY_GRP_TEN2       (9)
#define KEY_GRP_TEN3       (9)
#define KEY_GRP_TEN0       (9)
#define KEY_GRP_ENTER      (9)

#define KEY_GRP_XF1        (10)
#define KEY_GRP_XF2        (10)
#define KEY_GRP_XF3        (10)

#define KEY_GRP_XF4        (11)
#define KEY_GRP_XF5        (11)
#define KEY_GRP_INS        (11)

#define KEY_GRP_F1         (12)
#define KEY_GRP_F2         (12)
#define KEY_GRP_F3         (12)
#define KEY_GRP_F4         (12)

#define KEY_GRP_F5         (12)
#define KEY_GRP_F6         (13)
#define KEY_GRP_F7         (13)
#define KEY_GRP_F8         (13)
#define KEY_GRP_F9         (13)
#define KEY_GRP_F10        (13)

#define KEY_BIT_ESC        (1)
#define KEY_BIT_1          (2)
#define KEY_BIT_2          (3)
#define KEY_BIT_3          (4)
#define KEY_BIT_4          (5)
#define KEY_BIT_5          (6)
#define KEY_BIT_6          (7)

#define KEY_BIT_7          (0)
#define KEY_BIT_8          (1)
#define KEY_BIT_9          (2)
#define KEY_BIT_0          (3)
#define KEY_BIT_MINUS      (4)
#define KEY_BIT_HAT        (5)
#define KEY_BIT_YEN        (6)
#define KEY_BIT_BS         (7)

#define KEY_BIT_TAB        (0)
#define KEY_BIT_Q          (1)
#define KEY_BIT_W          (2)
#define KEY_BIT_E          (3)
#define KEY_BIT_R          (4)
#define KEY_BIT_T          (5)
#define KEY_BIT_Y          (6)
#define KEY_BIT_U          (7)

#define KEY_BIT_I          (0)
#define KEY_BIT_O          (1)
#define KEY_BIT_P          (2)
#define KEY_BIT_ATMARK     (3)
#define KEY_BIT_SQBR_LEFT  (4)
#define KEY_BIT_CR         (5)
#define KEY_BIT_A          (6)
#define KEY_BIT_S          (7)

#define KEY_BIT_D          (0)
#define KEY_BIT_F          (1)
#define KEY_BIT_G          (2)
#define KEY_BIT_H          (3)
#define KEY_BIT_J          (4)
#define KEY_BIT_K          (5)
#define KEY_BIT_L          (6)
#define KEY_BIT_SEMICOLON  (7)

#define KEY_BIT_COLON      (0)
#define KEY_BIT_SQBR_RIGHT (1)
#define KEY_BIT_X          (3)
#define KEY_BIT_C          (4)
#define KEY_BIT_V          (5)
#define KEY_BIT_B          (6)
#define KEY_BIT_N          (7)

#define KEY_BIT_M          (0)
#define KEY_BIT_COMMA      (1)
#define KEY_BIT_PERIOD     (2)
#define KEY_BIT_SLASH      (3)
#define KEY_BIT_UNDERSCORE (4)
#define KEY_BIT_SPACE      (5)
#define KEY_BIT_HOME       (6)
#define KEY_BIT_DEL        (7)

#define KEY_BIT_ROLLUP     (0)
#define KEY_BIT_ROLLDOWN   (1)
#define KEY_BIT_UNDO       (2)
#define KEY_BIT_LEFT       (3)
#define KEY_BIT_UP         (4)
#define KEY_BIT_RIGHT      (5)
#define KEY_BIT_DOWN       (6)
#define KEY_BIT_CLR        (7)

#define KEY_BIT_TEN7       (3)
#define KEY_BIT_TEN8       (4)
#define KEY_BIT_TEN9       (5)
#define KEY_BIT_TEN4       (7)

#define KEY_BIT_TEN5       (0)
#define KEY_BIT_TEN6       (1)
#define KEY_BIT_TEN1       (3)
#define KEY_BIT_TEN2       (4)
#define KEY_BIT_TEN3       (5)
#define KEY_BIT_TEN0       (7)

#define KEY_BIT_ENTER      (6)

#define KEY_BIT_XF1        (5)
#define KEY_BIT_XF2        (6)
#define KEY_BIT_XF3        (7)

#define KEY_BIT_XF4        (0)
#define KEY_BIT_XF5        (1)
#define KEY_BIT_INS        (6)

#define KEY_BIT_F1         (3)
#define KEY_BIT_F2         (4)
#define KEY_BIT_F3         (5)
#define KEY_BIT_F4         (6)
#define KEY_BIT_F5         (7)

#define KEY_BIT_F6         (0)
#define KEY_BIT_F7         (1)
#define KEY_BIT_F8         (2)
#define KEY_BIT_F9         (3)
#define KEY_BIT_F10        (4)

#define KEY_SCAN_CODE_ESC        ( KEY_GRP_ESC        * 8 + KEY_BIT_ESC        )
#define KEY_SCAN_CODE_1          ( KEY_GRP_1          * 8 + KEY_BIT_1          )
#define KEY_SCAN_CODE_2          ( KEY_GRP_2          * 8 + KEY_BIT_2          )
#define KEY_SCAN_CODE_3          ( KEY_GRP_3          * 8 + KEY_BIT_3          )
#define KEY_SCAN_CODE_4          ( KEY_GRP_4          * 8 + KEY_BIT_4          )
#define KEY_SCAN_CODE_5          ( KEY_GRP_5          * 8 + KEY_BIT_5          )
#define KEY_SCAN_CODE_6          ( KEY_GRP_6          * 8 + KEY_BIT_6          )

#define KEY_SCAN_CODE_7          ( KEY_GRP_7          * 8 + KEY_BIT_7          )
#define KEY_SCAN_CODE_8          ( KEY_GRP_8          * 8 + KEY_BIT_8          )
#define KEY_SCAN_CODE_9          ( KEY_GRP_9          * 8 + KEY_BIT_9          )
#define KEY_SCAN_CODE_0          ( KEY_GRP_0          * 8 + KEY_BIT_0          )
#define KEY_SCAN_CODE_MINUS      ( KEY_GRP_MINUS      * 8 + KEY_BIT_MINUS      )
#define KEY_SCAN_CODE_HAT        ( KEY_GRP_HAT        * 8 + KEY_BIT_HAT        )
#define KEY_SCAN_CODE_YEN        ( KEY_GRP_YEN        * 8 + KEY_BIT_YEN        )
#define KEY_SCAN_CODE_BS         ( KEY_GRP_BS         * 8 + KEY_BIT_BS         )

#define KEY_SCAN_CODE_TAB        ( KEY_GRP_TAB        * 8 + KEY_BIT_TAB        )
#define KEY_SCAN_CODE_Q          ( KEY_GRP_Q          * 8 + KEY_BIT_Q          )
#define KEY_SCAN_CODE_W          ( KEY_GRP_W          * 8 + KEY_BIT_W          )
#define KEY_SCAN_CODE_E          ( KEY_GRP_E          * 8 + KEY_BIT_E          )
#define KEY_SCAN_CODE_R          ( KEY_GRP_R          * 8 + KEY_BIT_R          )
#define KEY_SCAN_CODE_T          ( KEY_GRP_T          * 8 + KEY_BIT_T          )
#define KEY_SCAN_CODE_Y          ( KEY_GRP_Y          * 8 + KEY_BIT_Y          )
#define KEY_SCAN_CODE_U          ( KEY_GRP_U          * 8 + KEY_BIT_U          )

#define KEY_SCAN_CODE_I          ( KEY_GRP_I          * 8 + KEY_BIT_I          )
#define KEY_SCAN_CODE_O          ( KEY_GRP_O          * 8 + KEY_BIT_O          )
#define KEY_SCAN_CODE_P          ( KEY_GRP_P          * 8 + KEY_BIT_P          )
#define KEY_SCAN_CODE_ATMARK     ( KEY_GRP_ATMARK     * 8 + KEY_BIT_ATMARK     )
#define KEY_SCAN_CODE_SQBR_LEFT  ( KEY_GRP_SQBR_LEFT  * 8 + KEY_BIT_SQBR_LEFT  )
#define KEY_SCAN_CODE_CR         ( KEY_GRP_CR         * 8 + KEY_BIT_CR         )
#define KEY_SCAN_CODE_A          ( KEY_GRP_A          * 8 + KEY_BIT_A          )
#define KEY_SCAN_CODE_S          ( KEY_GRP_S          * 8 + KEY_BIT_S          )

#define KEY_SCAN_CODE_D          ( KEY_GRP_D          * 8 + KEY_BIT_D          )
#define KEY_SCAN_CODE_F          ( KEY_GRP_F          * 8 + KEY_BIT_F          )
#define KEY_SCAN_CODE_G          ( KEY_GRP_G          * 8 + KEY_BIT_G          )
#define KEY_SCAN_CODE_H          ( KEY_GRP_H          * 8 + KEY_BIT_H          )
#define KEY_SCAN_CODE_J          ( KEY_GRP_J          * 8 + KEY_BIT_J          )
#define KEY_SCAN_CODE_K          ( KEY_GRP_K          * 8 + KEY_BIT_K          )
#define KEY_SCAN_CODE_L          ( KEY_GRP_L          * 8 + KEY_BIT_L          )
#define KEY_SCAN_CODE_SEMICOLON  ( KEY_GRP_SEMICOLON  * 8 + KEY_BIT_SEMICOLON  )

#define KEY_SCAN_CODE_COLON      ( KEY_GRP_COLON      * 8 + KEY_BIT_COLON      )
#define KEY_SCAN_CODE_SQBR_RIGHT ( KEY_GRP_SQBR_RIGHT * 8 + KEY_BIT_SQBR_RIGHT )
#define KEY_SCAN_CODE_X          ( KEY_GRP_X          * 8 + KEY_BIT_X          )
#define KEY_SCAN_CODE_Z          ( KEY_GRP_Z          * 8 + KEY_BIT_Z          )
#define KEY_SCAN_CODE_C          ( KEY_GRP_C          * 8 + KEY_BIT_C          )
#define KEY_SCAN_CODE_V          ( KEY_GRP_V          * 8 + KEY_BIT_V          )
#define KEY_SCAN_CODE_N          ( KEY_GRP_N          * 8 + KEY_BIT_N          )
#define KEY_SCAN_CODE_B          ( KEY_GRP_B          * 8 + KEY_BIT_B          )

#define KEY_SCAN_CODE_M          ( KEY_GRP_M          * 8 + KEY_BIT_M          )
#define KEY_SCAN_CODE_COMMA      ( KEY_GRP_COMMA      * 8 + KEY_BIT_COMMA      )
#define KEY_SCAN_CODE_PERIOD     ( KEY_GRP_PERIOD     * 8 + KEY_BIT_PERIOD     )
#define KEY_SCAN_CODE_SLASH      ( KEY_GRP_SLASH      * 8 + KEY_BIT_SLASH      )
#define KEY_SCAN_CODE_UNDERSCORE ( KEY_GRP_UNDERSCORE * 8 + KEY_BIT_UNDERSCORE )
#define KEY_SCAN_CODE_SPACE      ( KEY_GRP_SPACE      * 8 + KEY_BIT_SPACE      )
#define KEY_SCAN_CODE_HOME       ( KEY_GRP_HOME       * 8 + KEY_BIT_HOME       )
#define KEY_SCAN_CODE_DEL        ( KEY_GRP_DEL        * 8 + KEY_BIT_DEL        )

#define KEY_SCAN_CODE_ROLLUP     ( KEY_GRP_ROLLUP     * 8 + KEY_BIT_ROLLUP     )
#define KEY_SCAN_CODE_ROLLDOWN   ( KEY_GRP_ROLLDOWN   * 8 + KEY_BIT_ROLLDOWN   )
#define KEY_SCAN_CODE_UNDO       ( KEY_GRP_UNDO       * 8 + KEY_BIT_UNDO       )
#define KEY_SCAN_CODE_LEFT       ( KEY_GRP_LEFT       * 8 + KEY_BIT_LEFT       )
#define KEY_SCAN_CODE_UP         ( KEY_GRP_UP         * 8 + KEY_BIT_UP         )
#define KEY_SCAN_CODE_RIGHT      ( KEY_GRP_RIGHT      * 8 + KEY_BIT_RIGHT      )
#define KEY_SCAN_CODE_DOWN       ( KEY_GRP_DOWN       * 8 + KEY_BIT_DOWN       )
#define KEY_SCAN_CODE_CLR        ( KEY_GRP_CLR        * 8 + KEY_BIT_CLR        )

#define KEY_SCAN_CODE_TEN7       ( KEY_GRP_TEN7       * 8 + KEY_BIT_TEN7       )
#define KEY_SCAN_CODE_TEN8       ( KEY_GRP_TEN8       * 8 + KEY_BIT_TEN8       )
#define KEY_SCAN_CODE_TEN9       ( KEY_GRP_TEN9       * 8 + KEY_BIT_TEN9       )
#define KEY_SCAN_CODE_TEN4       ( KEY_GRP_TEN4       * 8 + KEY_BIT_TEN4       )

#define KEY_SCAN_CODE_TEN5       ( KEY_GRP_TEN5       * 8 + KEY_BIT_TEN5       )
#define KEY_SCAN_CODE_TEN6       ( KEY_GRP_TEN6       * 8 + KEY_BIT_TEN6       )
#define KEY_SCAN_CODE_TEN1       ( KEY_GRP_TEN1       * 8 + KEY_BIT_TEN1       )
#define KEY_SCAN_CODE_TEN2       ( KEY_GRP_TEN2       * 8 + KEY_BIT_TEN2       )
#define KEY_SCAN_CODE_TEN3       ( KEY_GRP_TEN3       * 8 + KEY_BIT_TEN3       )
#define KEY_SCAN_CODE_ENTER      ( KEY_GRP_ENTER      * 8 + KEY_BIT_ENTER      )
#define KEY_SCAN_CODE_TEN0       ( KEY_GRP_TEN0       * 8 + KEY_BIT_TEN0       )

#define KEY_SCAN_CODE_XF1        ( KEY_GRP_XF1        * 8 + KEY_BIT_XF1        )
#define KEY_SCAN_CODE_XF2        ( KEY_GRP_XF2        * 8 + KEY_BIT_XF2        )
#define KEY_SCAN_CODE_XF3        ( KEY_GRP_XF3        * 8 + KEY_BIT_XF3        )

#define KEY_SCAN_CODE_XF4        ( KEY_GRP_XF4        * 8 + KEY_BIT_XF4        )
#define KEY_SCAN_CODE_XF5        ( KEY_GRP_XF5        * 8 + KEY_BIT_XF5        )
#define KEY_SCAN_CODE_INS        ( KEY_GRP_INS        * 8 + KEY_BIT_INS        )

#define KEY_SCAN_CODE_F1         ( KEY_GRP_F1         * 8 + KEY_BIT_F1         )
#define KEY_SCAN_CODE_F2         ( KEY_GRP_F2         * 8 + KEY_BIT_F2         )
#define KEY_SCAN_CODE_F3         ( KEY_GRP_F3         * 8 + KEY_BIT_F3         )
#define KEY_SCAN_CODE_F4         ( KEY_GRP_F4         * 8 + KEY_BIT_F4         )
#define KEY_SCAN_CODE_F5         ( KEY_GRP_F5         * 8 + KEY_BIT_F5         )

#define KEY_SCAN_CODE_F6         ( KEY_GRP_F6         * 8 + KEY_BIT_F6         )
#define KEY_SCAN_CODE_F7         ( KEY_GRP_F7         * 8 + KEY_BIT_F7         )
#define KEY_SCAN_CODE_F8         ( KEY_GRP_F8         * 8 + KEY_BIT_F8         )
#define KEY_SCAN_CODE_F9         ( KEY_GRP_F9         * 8 + KEY_BIT_F9         )
#define KEY_SCAN_CODE_F10        ( KEY_GRP_F10        * 8 + KEY_BIT_F10        )

#define KEY_SCAN_CODE_SHIFT_TAB    ( KEY_SCAN_CODE_TAB    + 0x100 )
#define KEY_SCAN_CODE_SHIFT_COMMA  ( KEY_SCAN_CODE_COMMA  + 0x100 )
#define KEY_SCAN_CODE_SHIFT_PERIOD ( KEY_SCAN_CODE_PERIOD + 0x100 )
#define KEY_SCAN_CODE_SHIFT_R      ( KEY_SCAN_CODE_R      + 0x100 )
#define KEY_SCAN_CODE_SHIFT_A      ( KEY_SCAN_CODE_A      + 0x100 )
#define KEY_SCAN_CODE_SHIFT_S      ( KEY_SCAN_CODE_S      + 0x100 )
#define KEY_SCAN_CODE_SHIFT_X      ( KEY_SCAN_CODE_X      + 0x100 )
#define KEY_SCAN_CODE_SHIFT_M      ( KEY_SCAN_CODE_M      + 0x100 )

#define KEY_SCAN_CODE_CTRL_P     ( KEY_SCAN_CODE_P + 0x200 )
#define KEY_SCAN_CODE_CTRL_F     ( KEY_SCAN_CODE_F + 0x200 )
#define KEY_SCAN_CODE_CTRL_V     ( KEY_SCAN_CODE_V + 0x200 )
#define KEY_SCAN_CODE_CTRL_N     ( KEY_SCAN_CODE_N + 0x200 )
#define KEY_SCAN_CODE_CTRL_B     ( KEY_SCAN_CODE_B + 0x200 )
#define KEY_SCAN_CODE_CTRL_M     ( KEY_SCAN_CODE_M + 0x200 )
#define KEY_SCAN_CODE_CTRL_XF1   ( KEY_SCAN_CODE_XF1 + 0x200 )
#define KEY_SCAN_CODE_CTRL_XF2   ( KEY_SCAN_CODE_XF2 + 0x200 )
#define KEY_SCAN_CODE_CTRL_XF3   ( KEY_SCAN_CODE_XF3 + 0x200 )
#define KEY_SCAN_CODE_CTRL_XF4   ( KEY_SCAN_CODE_XF4 + 0x200 )
#define KEY_SCAN_CODE_CTRL_XF5   ( KEY_SCAN_CODE_XF5 + 0x200 )

#define KEY_SNS_ESC        (1 << KEY_BIT_ESC        )
#define KEY_SNS_1          (1 << KEY_BIT_1          )
#define KEY_SNS_2          (1 << KEY_BIT_2          )
#define KEY_SNS_3          (1 << KEY_BIT_3          )
#define KEY_SNS_4          (1 << KEY_BIT_4          )
#define KEY_SNS_5          (1 << KEY_BIT_5          )
#define KEY_SNS_6          (1 << KEY_BIT_6          )

#define KEY_SNS_7          (1 << KEY_BIT_7          )
#define KEY_SNS_8          (1 << KEY_BIT_8          )
#define KEY_SNS_9          (1 << KEY_BIT_9          )
#define KEY_SNS_0          (1 << KEY_BIT_0          )
#define KEY_SNS_MINUS      (1 << KEY_BIT_MINUS      )
#define KEY_SNS_HAT        (1 << KEY_BIT_HAT        )
#define KEY_SNS_YEN        (1 << KEY_BIT_YEN        )
#define KEY_SNS_BS         (1 << KEY_BIT_BS         )

#define KEY_SNS_TAB        (1 << KEY_BIT_TAB        )
#define KEY_SNS_Q          (1 << KEY_BIT_Q          )
#define KEY_SNS_W          (1 << KEY_BIT_W          )
#define KEY_SNS_E          (1 << KEY_BIT_E          )
#define KEY_SNS_R          (1 << KEY_BIT_R          )
#define KEY_SNS_T          (1 << KEY_BIT_T          )
#define KEY_SNS_Y          (1 << KEY_BIT_Y          )
#define KEY_SNS_U          (1 << KEY_BIT_U          )

#define KEY_SNS_I          (1 << KEY_BIT_I          )
#define KEY_SNS_O          (1 << KEY_BIT_O          )
#define KEY_SNS_P          (1 << KEY_BIT_P          )
#define KEY_SNS_ATMARK     (1 << KEY_BIT_ATMARK     )
#define KEY_SNS_SQBR_LEFT  (1 << KEY_BIT_SQBR_LEFT  )
#define KEY_SNS_CR         (1 << KEY_BIT_CR         )
#define KEY_SNS_A          (1 << KEY_BIT_A          )
#define KEY_SNS_S          (1 << KEY_BIT_S          )

#define KEY_SNS_D          (1 << KEY_BIT_D          )
#define KEY_SNS_F          (1 << KEY_BIT_F          )
#define KEY_SNS_G          (1 << KEY_BIT_G          )
#define KEY_SNS_H          (1 << KEY_BIT_H          )
#define KEY_SNS_J          (1 << KEY_BIT_J          )
#define KEY_SNS_K          (1 << KEY_BIT_K          )
#define KEY_SNS_L          (1 << KEY_BIT_L          )
#define KEY_SNS_SEMICOLON  (1 << KEY_BIT_SEMICOLON  )

#define KEY_SNS_COLON      (1 << KEY_BIT_COLON      )
#define KEY_SNS_SQBR_RIGHT (1 << KEY_BIT_SQBR_RIGHT )
#define KEY_SNS_Z          (1 << KEY_BIT_Z          )
#define KEY_SNS_X          (1 << KEY_BIT_X          )
#define KEY_SNS_C          (1 << KEY_BIT_C          )
#define KEY_SNS_V          (1 << KEY_BIT_V          )
#define KEY_SNS_N          (1 << KEY_BIT_N          )
#define KEY_SNS_B          (1 << KEY_BIT_B          )

#define KEY_SNS_M          (1 << KEY_BIT_M          )
#define KEY_SNS_COMMA      (1 << KEY_BIT_COMMA      )
#define KEY_SNS_PERIOD     (1 << KEY_BIT_PERIOD     )
#define KEY_SNS_SLASH      (1 << KEY_BIT_SLASH      )
#define KEY_SNS_UNDERSCORE (1 << KEY_BIT_UNDERSCORE )
#define KEY_SNS_SPACE      (1 << KEY_BIT_SPACE      )
#define KEY_SNS_HOME       (1 << KEY_BIT_HOME       )
#define KEY_SNS_DEL        (1 << KEY_BIT_DEL        )

#define KEY_SNS_ROLLUP     (1 << KEY_BIT_ROLLUP     )
#define KEY_SNS_ROLLDOWN   (1 << KEY_BIT_ROLLDOWN   )
#define KEY_SNS_UNDO       (1 << KEY_BIT_UNDO       )
#define KEY_SNS_LEFT       (1 << KEY_BIT_LEFT       )
#define KEY_SNS_UP         (1 << KEY_BIT_UP         )
#define KEY_SNS_RIGHT      (1 << KEY_BIT_RIGHT      )
#define KEY_SNS_DOWN       (1 << KEY_BIT_DOWN       )
#define KEY_SNS_CLR        (1 << KEY_BIT_CLR        )

#define KEY_SNS_TEN7       (1 << KEY_BIT_TEN7       )
#define KEY_SNS_TEN8       (1 << KEY_BIT_TEN8       )
#define KEY_SNS_TEN9       (1 << KEY_BIT_TEN9       )
#define KEY_SNS_TEN4       (1 << KEY_BIT_TEN4       )

#define KEY_SNS_TEN5       (1 << KEY_BIT_TEN5       )
#define KEY_SNS_TEN6       (1 << KEY_BIT_TEN6       )
#define KEY_SNS_TEN1       (1 << KEY_BIT_TEN1       )
#define KEY_SNS_TEN2       (1 << KEY_BIT_TEN2       )
#define KEY_SNS_TEN3       (1 << KEY_BIT_TEN3       )
#define KEY_SNS_ENTER      (1 << KEY_BIT_ENTER      )
#define KEY_SNS_TEN0       (1 << KEY_BIT_TEN0       )

#define KEY_SNS_XF1        (1 << KEY_BIT_XF1        )
#define KEY_SNS_XF2        (1 << KEY_BIT_XF2        )
#define KEY_SNS_XF3        (1 << KEY_BIT_XF3        )

#define KEY_SNS_XF4        (1 << KEY_BIT_XF4        )
#define KEY_SNS_XF5        (1 << KEY_BIT_XF5        )
#define KEY_SNS_INS        (1 << KEY_BIT_INS        )

#define KEY_SNS_F1         (1 << KEY_BIT_F1         )
#define KEY_SNS_F2         (1 << KEY_BIT_F2         )
#define KEY_SNS_F3         (1 << KEY_BIT_F3         )
#define KEY_SNS_F4         (1 << KEY_BIT_F4         )
#define KEY_SNS_F5         (1 << KEY_BIT_F5         )

#define KEY_SNS_F6         (1 << KEY_BIT_F6         )
#define KEY_SNS_F7         (1 << KEY_BIT_F7         )
#define KEY_SNS_F8         (1 << KEY_BIT_F8         )
#define KEY_SNS_F9         (1 << KEY_BIT_F9         )
#define KEY_SNS_F10        (1 << KEY_BIT_F10        )

#endif